version: "3"

services:
  loadbalancer:
    build:
      dockerfile: Dockerfile_nginx
      context: .
    image: ecomnginx:latest
    container_name: loadbalancer
    networks:
      - ecomnet
    ports:
      - 80:80
    depends_on:
      - ecomapp

  ecomappdb:
    image: mysql:latest
    container_name: ecomappdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - ecomnet

  ecomapp:
    build:
      dockerfile: Dockerfile
      context: .
    image: ecomimage:latest
    container_name: ecomapp
    command: bash -c "./superuser.sh"
    links:
      - "ecomappdb:ecomappdb"
    depends_on:
      - ecomappdb
    ports:
      - 8000:8000
    volumes:
      - ecomvol:/code
    networks: 
      - ecomnet 

volumes:
  mysql_data:
  ecomvol:
networks: 
  ecomnet:
